'use client';
import {useState} from 'react';
import {Heart,ArrowDown,ArrowUpRight,Sparkles} from 'lucide-react';
const notes=[['Tu sonrisa','Si pudiera pedirle algo a este día, sería que te regalara tantas sonrisas como las que tú me provocas.'],['Lo cotidiano','Me gusta pensar que lo nuestro también vive en las cosas pequeñas: un mensaje, un ratito juntos, las ganas de saber cómo estás.'],['Elegirte','Entre todas las cosas bonitas que pueden pasarme, seguir compartiendo mis días contigo es una de mis favoritas.'],['Sin prisa','Quiero seguir conociéndote. Aprender lo que te hace feliz, escuchar tus historias y descubrir contigo todo lo que viene.'],['Cuidarnos','Quiero poner de mi parte para que lo nuestro tenga cariño, honestidad y espacio para ser nosotros mismos.'],['Lo que viene','No sé cuántas aventuras nos esperan. Pero me ilusiona muchísimo pensar que todavía tenemos tantas primeras veces por vivir.']];
export default function Home(){const [opened,setOpened]=useState(false);const [seen,setSeen]=useState<number[]>([]);const [active,setActive]=useState<number|null>(null);const [ending,setEnding]=useState(false);return <main>
<div className="stardust" aria-hidden="true">{Array.from({length:48},(_,i)=><i key={i} style={{left:`${(i*37.7)%100}%`,top:`${(i*23.3)%100}%`,animationDelay:`${i%7}s`}}/>)}</div>
<header><a href="#" className="monogram" aria-label="Michelle y Arian">m<span>&</span>a</a><span>UNA PEQUEÑA INFINIDAD</span><Heart size={18} strokeWidth={1}/></header>
<section className="hero"><p className="eyebrow">PARA MICHELLE · DE ARIAN</p><div className="anniversary"><span>02</span><p>meses de nosotros</p></div><h1>Qué bonito<br/>que seas <em>tú.</em></h1><p className="intro">Hay personas que hacen los días diferentes.<br/>Tú haces los míos más bonitos.</p><a className="pill" href="#carta" onClick={()=>setOpened(true)}>Tengo algo para ti <ArrowDown size={17}/></a><div className="hero-bottom"><span>NUESTRA FECHA · 09/07/2026</span><span>ESTO ES SOLO EL COMIENZO ↘</span></div></section>
<section id="carta" className="letter-section"><div className="section-heading"><span className="eyebrow">01 / LO QUE QUIERO DECIRTE</span><span aria-hidden="true">♡</span></div><div className="letter-wrap"><div className="letter-caption"><h2>Un pedacito<br/>de mi <em>corazón.</em></h2><p>Para leer despacito.<br/>Como un abrazo que dura un poquito más.</p></div><article className="letter">{!opened?<button className="open-letter" onClick={()=>setOpened(true)}><Heart size={34}/><span>Michelle, esta carta es tuya</span><u>Abrir mi carta</u></button>:<div className="letter-content"><span className="paper-label">CON TODO MI CARIÑO</span><h3>Mi Michelle,</h3><p>Felices dos meses, amor.</p><p>Quería regalarte algo que pudieras abrir y volver a leer cada vez que quisieras recordar cuánto significas para mí.</p><p>Desde aquel 9 de julio estamos escribiendo una historia que me hace sonreír. Dos meses pueden sonar a poquito, pero para mí son una razón enorme para celebrar.</p><p>Me hace feliz que estemos construyendo algo nuestro, a nuestra manera y a nuestro ritmo. Hoy quiero que sepas que me importas, que me encanta tenerte en mi vida y que tengo muchas ganas de seguir compartiendo momentos contigo.</p><p>Gracias por ser tú. Por formar parte de esta historia que apenas empieza y que ya quiero tanto.</p><p className="signature">Con amor,<br/><em>Arian</em><Heart size={19}/></p></div>}</article></div></section>
<section className="messages"><p className="eyebrow">02 / PEQUEÑAS COSAS, MUCHO AMOR</p><h2>Seis mensajitos.<br/>Todos <em>para ti.</em></h2><p>Toca cada uno. Dejé un poquito de cariño adentro.</p><div className="note-grid">{notes.map(([title,body],i)=><button key={title} className={`note ${active===i?'active':''}`} aria-expanded={active===i} onClick={()=>{setActive(active===i?null:i);setSeen(s=>s.includes(i)?s:[...s,i]);}}><span className="note-top"><span>0{i+1}</span>{seen.includes(i)?<Heart size={18} fill="currentColor"/>:<ArrowUpRight size={20}/>}</span><h3>{title}</h3>{active===i?<p>{body}</p>:<span className="note-hint">{seen.includes(i)?'Volver a leer':'Un mensaje para ti'}</span>}</button>)}</div><p className="count" aria-live="polite">{seen.length} de 6 pequeños abrazos descubiertos</p></section>
<section className="finale"><Sparkles size={25}/><p className="eyebrow">03 / Y ANTES DE QUE TE VAYAS…</p><h2>Mi parte favorita<br/>es que esto <em>continúa.</em></h2><p>Por lo que ya somos.<br/>Y por todo lo bonito que nos queda.</p><button className="pill" onClick={()=>setEnding(!ending)} aria-expanded={ending}>{ending?'Guardar este abrazo':'Un último abrazo'} <Heart size={18}/></button>{ending&&<div className="last-message" role="status"><span>Te quiero, Michelle.</span><p>Si estuviera contigo ahora, esta parte sería un abrazo largo.<br/>Mientras tanto, te dejo estas palabras y todo mi cariño.</p><strong>Felices dos meses, mi amor. ♡</strong></div>}</section><footer><span>MICHELLE & ARIAN</span><span>Hecho con amor, para ti.</span><span>09/07/2026 · ♡</span></footer></main>}
